name: dotnet package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/KSB.Results/appsettings.json'
          name: "DataContext"
          connectionstring: "${{ secrets.CONNECTION_STRING }}"
      - name: cache-nugets
        uses: actions/cache@v3
        id: cache-nugets
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore
        if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
        run: dotnet restore
      - name: publish
        run: dotnet publish --configuration Release --no-restore --output bin\output --self-contained false
      - name: publish ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.results.ksb.org.pl
          username: ksb-ftp
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./bin/output/
          server-dir: ./results.ksb.org.pl/wwwroot/

