name: dotnet package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: edit connection string
        uses: benday-inc/edit-dbconnstr-in-appsettings@main
        with:
          pathtosettingsfile: '${{ github.workspace }}/KSB.Results/appsettings.json'
          name: "default"
          connectionstring: "${{ secrets.CONNECTION_STRING }}"
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      - name: publish
        run: dotnet publish --arch x64 --configuration Release --output bin\output --self-contained true --os win
      - name: publish ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.results.ksb.org.pl
          username: ksb-ftp
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./KSB.Results/bin/output
          server-dir: ./

